language: node_js
node_js:
  - "10"
cache:
  directories:
    - server/node_modules
services:
  - mysql
before_install: 
 - cd server 
 - mysql -u root --password="" < test/travis.sql
script:
- npm test
- npm run lint
after_success: 
- npm run coverage
after_failure:
- npm run coverage
