language: node_js
node_js:
  - "10"
cache:
  directories:
    - server/node_modules
services:
  - mysql
before_install: 
 - cd server 
# - mysql -u root --password="" < test/travis.sql
script:
- npm test
after_success: 
- npm run coverage
#- eslint --fix app.js routes/** test/**